name: Build

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: |
          ${{ secrets.DEPLOY_KEY_EDGE_FN_SWIFT }}
          ${{ secrets.DEPLOY_KEY_SUBSTRATA_SWIFT }}
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

